### ISSUE TITLE
Looks like wrong URL format used for `anime_url`

### ISSUE THREAD

**Issue by NEK-RA** [vypivshiy/ani-cli-ru#1]
## Appeared error
![stacktrace](https://user-images.githubusercontent.com/21460603/140649427-b4ca3a16-5ab2-4b87-abcb-525033fbbd6c.jpeg)

## OS
OpenSUSE Leap 15.3 (64-bit)

## Python
Python version 3.6.13

## ani-cli-ru version
Cloned latest commit - https://github.com/vypivshiy/ani-cli-ru/commit/0b8c068d7c32fe79ad199ae59ee33f5b8b8d9a4e

## Reproduce steps
1. run `anicli-ru`
2. input any anime title, i.e. `bleach`
3. found 2 results, requested `Choose anime: 1 - 2`
4. inserted `1` without any additional symbols
5. pressed enter
6. got error

## Comments
1. `anicli-ru` was launched without any additional arguments
2. the search itself working as well as opening provided in [README](https://github.com/vypivshiy/ani-cli-ru/blob/master/README.md) resource in browser **without proxy**, so the proxy was not used

**Comment by vypivshiy** [comment]
Hi! I fix the script and add basic unittests.
P.S Bleach episodes (~200+) will not work, they are hosted on kodik balancer (
