### ISSUE TITLE
не работает парсер AnimeGo

### ISSUE THREAD

**Issue by Tabyretka** [vypivshiy/ani-cli-ru#11]
Не работает парсер AnimeGo. Отдает 403 код, на сайт добавили защиту от ddos-guard.

**Comment by vypivshiy** [comment]
Привет!

Я не знаю как решить эту проблему простым удобным способом на уровне программного интерфейса, не применяя selenium или ручную подстановку cookie файла.

Если кто-то поможет решить проблему (от советов с инструкцией до pull request), то будет исправление

Как временное решение могу посоветовать использовать альтернативные парсеры, так как в приоритете нет задачи делать обход ddos-guard.

**Comment by vypivshiy** [comment]
Закрываю Issue, так как Animego иногда включают ddos защиту (раньше cloudflare, сейчас ddos guard).
В проекте вряд ли будут использоваться механизмы обхода ddos, а большее что могу сделать - [добавить hook на все запросы и выкинуть предупреждение если будут проблемы](https://github.com/vypivshiy/ani-cli-ru/blob/master/anicli_ru/_http.py#L24).

По желанию можете модифицировать хук в объекте сессии и выкидывать ошибку, например.
