### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by JedySketi** [vypivshiy/ani-cli-ru#16]
У меня ошибка при установки описанная выше. Что мне делать

**Comment by vypivshiy** [comment]
Привет! Данных недостаточно, чтобы подсказать и дать рекомендации как решить проблему
1. Лог ошибки, какие шаги действий произведены?
2. Какая ОС (поддержка windows отсутствует в master и pypi версии)?
3. Установлен mpv плеер?
4. Региональное местонахождение ip адреса, так как есть проблемы с работой **не СНГ** ip адресами, с анилибрией обратная ситуация естественно
Дополните issue

**Comment by FattyNess** [comment]
Тоже, что и #23

> Попробуй  `$ pipx install  --system-site-packages anicli-ru`
