### ISSUE TITLE
Cant install anicli

### ISSUE THREAD

**Issue by brxxlstxrs** [vypivshiy/ani-cli-ru#23]
after pep668 pip recommend `pipx` to install any packages
idk if this is related or not - `pipx` doesn't see `requests` module it the way ' thinks it is non-builtin
mb this cuz `requests` passed in `requirements.txt`
![2023-06-28-23:26:41-screenshot](https://github.com/vypivshiy/ani-cli-ru/assets/92815065/1d75716d-4e7d-428c-9a3f-f323036e9ea4)

**Comment by FattyNess** [comment]
Попробуй ` $ pipx install  --system-site-packages anicli-ru`
