### ISSUE TITLE
Error with module

### ISSUE THREAD

**Issue by JumperYUI** [vypivshiy/ani-cli-ru#3]
Здравствуй. У меня ошибка с модулем, а точнее ModuleNotFoundError: No module named 'setuptools'. Помоги пожалуйста.

**Comment by raitonoberu** [comment]
`pip` установлен? Выполни `python3 -m ensurepip --upgrade`. Если не поможет, после этого `python3 -m pip install -U setuptools`. 

Теперь можешь установить рабочий форк, пока автор не мержнул [PR](https://github.com/vypivshiy/ani-cli-ru/pull/4):
```sh
python3 -m pip install https://github.com/raitonoberu/ani-cli-ru/archive/refs/heads/master.zip
```

**Comment by vypivshiy** [comment]
Опубликовал обновление на pypi.
Чтобы обновить библиотеку, запустие заново Makefile
`sudo make`
или обновите библиотеку через pip
`python3 -m pip install --upgrade anicli-ru`
Если всё также будут проблемы, создайте новый issue с описанием.
