### ISSUE TITLE
add --url argument

### ISSUE THREAD

**Issue by rumly111** [vypivshiy/ani-cli-ru#36]
Если у меня уже есть ссылка на аниме (например скопировал из браузера), то хотелось бы запустить например
`anicli --url https://animego.org/anime/provozhayuschaya-v-posledniy-put-friren-2430` и сразу получить список эпизодов, пропуская шаг поиска.

Если пойти дальше, можно также поддержать ссылки https://animego.org/anime/random и https://www.anilibria.tv/public/random.php

**Comment by rumly111** [comment]
или можно добавить в клиент команду `url <https://...>`

**Comment by vypivshiy** [comment]
привет, эта функциональность не запланирована. 

для специфического использования в том числе и в своих проектах можете использовать [api интерфейс](https://github.com/vypivshiy/anicli-api)

**Comment by rumly111** [comment]
ok
