### ISSUE TITLE
[eggella] Как сделать, чтобы текст не прыгал вверх?

### ISSUE THREAD

**Issue by rumly111** [vypivshiy/ani-cli-ru#37]
Насколько я понял, сейчас клиент старается позиционировать текст в консоли так, чтобы список был посередине экрана. Где и что поменять в коде, чтобы внизу не оставалось пустое место? Как видно на картинке, список длинный, на экран не влезает, но текст всё равно смещается вверх. 

![screenshot](https://github.com/vypivshiy/ani-cli-ru/assets/8035743/86a5ad9a-ef4b-4848-8f8e-979e271ea875)

После того, как напечатался список, слово "~/ongoing" должно оставаться внизу экрана, чтобы больше влезло полезной информации.

Если мой скриншот кажется странным, это потому что я внёс изменение в код, чтобы список из >20 элементов не сокращался.

**Comment by vypivshiy** [comment]
Логика вывода результатов не связана с eggella библиотекой. Вывод реализован в самом клиенте и просто "в лоб" печатает все результаты: [anicli/view.py](https://github.com/vypivshiy/ani-cli-ru/blob/master/anicli/views.py#L35)

Эта библиотека написана поверх python-prompt-toolkit для управления вводом (input/prompt) по образу и подобию flask и фреймворков для чатботов на базе декораторной магии, потому что на тот момент времени не было готовых решений по следующим критериям:

- кроссплатформенность: поддержка linux, mac, windows
- удобный программный интерфейс (эту проблему решил удолетворительно если не совсем плохо)
- на тот момент времени фреймворк textual был сырой и не очень пригодным для применения.

**Comment by rumly111** [comment]
я копался часа 2, но так и не нашёл, как это сделать.

**Comment by rumly111** [comment]
в общем разобрался. у функции/метода `prompt` есть параметер `reserve_space_for_menu` , который по умолчанию 8 . Выходит, дополнительное пространство резервируется для всплывающего меню с вариантами автодополнения. Т.к. мне это не нужно, я выставил `reserve_space_for_menu=1` и получил нужное для меня поведение.
