### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by JumperYUI** [vypivshiy/ani-cli-ru#5]
Не успел сказать тот раз "спасибо" так-что: Спасибо. Проблема отказывается работь "Not found!". Программу я пересобирал, обновлял( зависимости и ос) в том числе. Все бестолку ! Помогите плиз

**Comment by vypivshiy** [comment]
По умолчанию скрипт парсит с сайта [animego.org](https://animego.org)
Специально добавил в последнем обновлении резервный парсер под другой сайт, так как на первом иногда включают cloudflare и из-за этого скрипт ломается.
Запустите скрипт с параметром `-s 2` или `--source 2` , чтобы парсить с [animania.online](https://animania.online). В этом режиме могут быть некоторые недочёты (например, на данный момент после получения онгоингов не берутся видео), но минимальная работоспособность присутствует.

`anicli-ru -s 2`

**Comment by JumperYUI** [comment]
> 

Выражаю глубочайшую благодарность
