### ISSUE TITLE
это че блять было

### ISSUE THREAD

**Issue by axax-loll** [vypivshiy/ani-cli-ru#52]
![image](https://github.com/user-attachments/assets/788edf07-b0ef-43f1-9709-b01fee26e967)

**Comment by Hezaki** [comment]
Реально

**Comment by vypivshiy** [comment]
временно выдали спамфлаг за оффтоп в репозитории winamp, я извинялся в поддержке и его сняли

**Comment by axax-loll** [comment]
понял, а то я уже обосрался что ты проект забросил

**Comment by axax-loll** [comment]
понял, а то я уже обосрался что ты проект забросил
