### ISSUE TITLE
"episodes not available" when there are episodes

### ISSUE THREAD

**Issue by rumly111** [vypivshiy/ani-cli-ru#53]
Проект ещё жив? Хотел посмотреть все сезоны "Звучи, эуфониум!", на animego, и некоторые сезоны/овы находит, но эпизоды не показывает.

Такое уже замечал на других тайтлах. Единственную закономерность, которую заметил, это вроде бы номерные сезоны работают нормально, а ОВА и полнометражки (сезоны с 1 серией) глючат.

**Comment by kolobok5447** [comment]
Может быть серии а то и аниме недоступно в твоём регеоне. Попробуй использовать прокси. Там вроде была команда на это.

**Comment by vypivshiy** [comment]
Привет!

> Проект ещё жив? 

Актуальная реализация работает, поэтому да

Проблемы с доступом к некоторым тайтлам из-за региональных ограничений. Я минимально проверял смену геолокации при помощи vpn/proxy и максимально выдает результат из стран Прибалтики (Латвия, Литва, Эстония). Возможно на других регионах лучше работает, я не проверял

**Comment by rumly111** [comment]
> Проблемы с доступом к некоторым тайтлам из-за региональных ограничений

Это когда выдаёт "Доступ к АПИ ограничен в вашем регионе" ?? Я задал Московский прокси, и действительно такое было. А также "no episodes available". Но на тот же тайтл без прокси просто выдаёт "no episodes available" .

Попробуйте поискать "hibike" и посмотреть, все ли сезоны/фильмы/овы отображаются. Если да, то таки дело в проксях. Я пробовал подставлять американские, европейские, но что-то не работало, программа "зависала" на запросе. Откуда вы берёте их?

**Comment by vypivshiy** [comment]
> > Проблемы с доступом к некоторым тайтлам из-за региональных ограничений
> 
> Это когда выдаёт "Доступ к АПИ ограничен в вашем регионе" ?? Я задал Московский прокси, и действительно такое было. А также "no episodes available". Но на тот же тайтл без прокси просто выдаёт "no episodes available" .
> 
> Попробуйте поискать "hibike" и посмотреть, все ли сезоны/фильмы/овы отображаются. Если да, то таки дело в проксях. Я пробовал подставлять американские, европейские, но что-то не работало, программа "зависала" на запросе. Откуда вы берёте их?

Забыл добавить, что на странах Западной Европы и Америке точно не будет работать: kodik, aniboom плееры точно ограничивают.
Надо выбирать с СНГ/Прибалтики геолокацию. Предполагаю, что на прибалтике будет меньше всего ограничений

**Comment by rumly111** [comment]
> Предполагаю, что на прибалтике будет меньше всего ограничений

Допустим выбираю из этих списков:
https://spys.one/free-proxy-list/LT/
https://spys.one/free-proxy-list/LV/
https://spys.one/free-proxy-list/EE/

Выбираю только socks5 и https(анонимные), думаю ходить на animego.org через http прокси не стоит. Но я так и не нашёл рабочий.

**Comment by vypivshiy** [comment]
С бесплатными проксями и обходами помочь не смогу. Поэтому или искать рабочие или другие источники использовать.

У меня было в планах добавить rutube. Да странно звучит, но там есть тематические каналы как бесплатный кинотеатр без необходимости обхода РКН ограничений

Готового экстрактора пока нет, но если очень хочется опробовать - вот временное решение:

1. нужен установленный yt-dlp (и mpv соответственно)
2. зайти на плейлист (например, https://rutube.ru/plst/598118/)
3. пролистать страницу вниз до конца
4. открыть консоль разработчика (ctrl + shift + i), ввести код:

```js
"mpv " + Array.from(document.querySelectorAll('.wdp-playlist-video-card-module__title')).map(e => `"https://rutube.ru${e.attributes['href'].nodeValue}"`).join(' ')
```

готовую команду вбить в терминал, играт смотрет

**Comment by rumly111** [comment]
наш разговор не туда зашёл. я вообще не в росии живу, и рутуб мне не нужен. я не могу понять, отсутствие эпизодов это глюк программы, или просто блокировка, и можно использовать прокси. автор, пожалуйста проверь именно "Звучи, Эуфониум" и все ОВА, если у тебя работает, тикет можно закрывать.

**Comment by axax-loll** [comment]
![image](https://github.com/user-attachments/assets/3230a7b0-9d9b-49b5-9285-fc22a2fc6f3b)
видео воспоризводится, возможно что то на твоей стороне, попробуй переустановить прогу или попробовать другой сурс
