### ISSUE TITLE
Ошибка в выборе серий/озвучки

### ISSUE THREAD

**Issue by gapisani** [vypivshiy/ani-cli-ru#6]
При использовании с флагом -i включается та же серия, но с другой озвучкой, без этого флага после завершения серии включается меню с выбором озвучки.

**Comment by vypivshiy** [comment]
Да, такая проблема есть с парсером animego, я эту фичу только тестил на animania. Надо думать как улучшить эту фичу

**Comment by vypivshiy** [comment]
Накинул костыльное решение, обновитесь через pip или флаг -U и перезапустите сессию терминала
`pip install install anicli-ru -U`
или
`anicli-ru -U`
