### ISSUE TITLE
Частично не работает

### ISSUE THREAD

**Issue by den9995** [vypivshiy/ani-cli-ru#8]
с сайта animego, kodik не работает на 23,24,25,26 сериях Евангелиона.
выдаёт следующее сообщение:
[ffmpeg] https: HTTP error 404 Not Found                                                                                Failed to open https://cloud.kodik-storage.com/useruploads/ec8f578c-927e-49c8-8b23-d3cace6363aa/344bd9d788f050c5b1e283120e137d74:2022043006/720.mp4:hls:manifest.m3u8.                                                                                                                                                                                                  
проверено windows 10, python 3.10; arch, python 3.10

**Comment by vypivshiy** [comment]
Привет! Ошибка была в том, что на kodik не лежат нужные серии в 720p, а в наличии только 480p и ниже. 
```python
import requests
requests.get("https://cloud.kodik-storage.com/useruploads/.../720.mp4:hls:manifest.m3u8").status_code  # 404
requests.get("https://cloud.kodik-storage.com/useruploads/.../480.mp4:hls:manifest.m3u8").status_code  # 200
```

Добавил дополнительную проверку валидности ссылки для этого плеера с понижением качества от 720 до 360 и залил исправление на pypi, обновитесь.
